config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get     '/regisztracio',                 to: 'users#new'
  post    '/regisztracio',                 to: 'users#create'
  
  scope(path_names: { edit: 'szerkesztes' }) do
    resources :users, path: 'felhasznalok', except: [:new, :create]
  end

  get    '/bejelentkezes',   to: 'session#new'
  post   '/bejelentkezes',   to: 'session#create'
  delete '/kijelentkezes',   to: 'session#destroy'

  scope(path_names: { new: 'uj', edit: 'szerkesztes' }) do
    resources :posts, path: 'blog'
  end

  scope(path_names: { new: 'uj', edit: 'szerkesztes'}) do
    resources :recipes, path: 'receptek'
  end

  get   '/kategoria/:id', to: 'recipe_categories#show', as: 'recipe_category'
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :featured_image, ImageUploader
  belongs_to :user
  has_and_belongs_to_many :recipe_category
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true

  private
    def image_size_validation
      errors[:featured_image] << "nem lehett nagyobb, mint 1 MB" if featured_image.size > 1.0.megabytes
    end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :recipes, dependent: :destroy
  attr_accessor :remember_token
  before_save   :downcase_email
  validates :username, presence: true, length: {maximum: 50, minimum: 4}, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: {maximum: 255, minimum: 5}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates_processing_of :avatar
  validate :image_size_validation

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    def image_size_validation
      errors[:avatar] << "nem lehett nagyobb, mint 500 KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = Recipe.order('recipes.created_at DESC').paginate(page: params[:page])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(post_params)
    if @recipe.save
      flash[:success] = "Receptjék sikeresen mentettük!"
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(post_params)
      flash[:success] = 'Recept frissítve.'
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @lastrecipes = Recipe.order('recipes.created_at DESC').limit(5)
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recept törölve."
    redirect_to recipes_url
  end

  private

    def post_params
      params.require(:recipe).permit(:title, :description, :ingredients, :serves, :prep_time, :cooking_time, :featured_image, :user_id, {:recipe_category_ids => []})
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<div class="col-12 col-md-4">
  <article id="recipe-<%= recipe.id %>" class="recipe-card">
    <div class="thumbnail">
      <% if recipe.featured_image_url %>
        <a href="<%= recipe_path(recipe.id) %>" style="background-image: url(<%= recipe.featured_image_url %>)"></a>
      <% else %>
        <a href="<%= recipe_path(recipe.id) %>"></a>
      <% end %>
    </div>

    <div class="header-box">
      <span class="cat">
        <% for category_id in recipe.recipe_category_ids %>
          <%= link_to RecipeCategory.find(category_id).name, recipe_category_path(category_id), class: 'cat-name' %>
        <% end %>
      </span>
    </div>

    <h2 class="title">
      <%= link_to recipe.title, recipe_path(recipe.id) %>
    </h2>
  </article>
</div>

app/views/recipes/edit.html.erb
<% provide(:title, "Recept szerkesztése") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <% if @recipe.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <p><%= pluralize(@recipe.errors.count, "hiba") %> merült fel a közzététel során:</p>

        <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_for(@recipe, url: {action: :update}) do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Cím:' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'recipe_category_id', 'Kategória:' %>
          <%= collection_select :recipe, :recipe_category_ids, RecipeCategory.all, :id, :name, {:include_blank => false}, {:multiple => true, :name=>'recipe[recipe_category_ids][]',:selected => 0, class: 'form-control', id: 'recipe_category_id'} %>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Leírás:' %>
          <%= f.text_area :description, id: 'froala', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :ingredients, 'Hozzávalók:' %>
          <%= f.text_area :ingredients, id: 'igredients', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :serves, 'Adag:' %>
          <%= f.text_field :serves, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :prep_time, 'Előkészületi idő (perc):' %>
          <%= f.text_field :prep_time, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :cooking_time, 'Elkészítési idő (perc):' %>
          <%= f.text_field :cooking_time, class: 'form-control' %>
        </div>
        <div class="form-group text-center">
          <% if f.object.featured_image? %>
            <%= image_tag f.object.featured_image.thumb.url, class: 'img-fluid' %>
          <% end %>
          <div class="form-avatar">
            <%= f.label :featured_image, 'Kép feltöltése' %>
            <%= f.file_field :featured_image, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Frissítés", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% provide(:title, "Receptek") %>

<seciton id="recipes">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="row recipes">
          <%= render @recipes %>        
        </div>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</seciton>

app/views/recipes/new.html.erb
<% provide(:title, "Új recept") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <% if @recipe.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <p><%= pluralize(@recipe.errors.count, "hiba") %> merült fel a közzététel során:</p>

        <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_for(@recipe, url: {action: :create}) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
          <%= f.label :title, 'Cím:' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label 'recipe_category_id', 'Kategória:' %>
          <%= collection_select :recipe, :recipe_category_ids, RecipeCategory.all, :id, :name, {:include_blank => false}, {:multiple => true, :name=>'recipe[recipe_category_ids][]',:selected => 0, class: 'form-control', id: 'recipe_category_id'} %>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Leírás:' %>
          <%= f.text_area :description, id: 'froala', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :ingredients, 'Hozzávalók:' %>
          <%= f.text_area :ingredients, id: 'igredients', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :serves, 'Adag:' %>
          <%= f.text_field :serves, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :prep_time, 'Előkészületi idő (perc):' %>
          <%= f.text_field :prep_time, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :cooking_time, 'Elkészítési idő (perc):' %>
          <%= f.text_field :cooking_time, class: 'form-control' %>
        </div>
        <div class="form-group text-center">
          <div class="form-avatar">
            <%= f.label :featured_image, 'Kép feltöltése' %>
            <%= f.file_field :featured_image, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Küldés", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% provide(:title, @recipe.title) %>

<section id="recipe">
  <div class="container">
    <div class="row">
      <div class="col-8">
        <div class="page-content">
          <article id="recipe-<%= @recipe.id %>" class="recipe">
            <div class="header-standard text-center">
              <div class="category">
                <span class="cat">
                  <% for category_id in @recipe.recipe_category_ids %>
                    <%= link_to RecipeCategory.find(category_id).name, recipe_category_path(category_id), class: 'cat-name' %>
                  <% end %>
                </span>
              </div>
              <h2 class="recipe-title"><%= @recipe.title %></h2>
              <div class="recipe-meta">
                <span class="author">feltöltő: <%= link_to (@recipe.user.lastname + ' ' + @recipe.user.firstname).html_safe, user_path(@recipe.user.id) %></span>
                <span class="created_at"><%= l @recipe.created_at %></span>
              </div>
            </div>
            <% if @recipe.featured_image.url %>
              <%= image_tag @recipe.featured_image.url, class: 'img-fluid' %>
            <% end %>
            <div class="recipe-wrapper">
              <div class="recipe-inner">
                <div class="recipe-header">
                  <h2><%= @recipe.title %></h2>
                  <div class="recipe-meta">
                    <span><i class="fa fa-user"></i> Adag: <%= @recipe.serves %></span>
                    <span><i class="fa fa-clock-o"></i> Előkészítés: <%= @recipe.prep_time %> perc</span>
                    <span><i class="fa fa-clock-o"></i> Elkészítés: <%= @recipe.cooking_time %> perc</span>
                  </div>
                </div>

                <div class="recipe-ingredients">
                  <h3 class="recipe-title">Hozzávalók</h3>
                  <%= (@recipe.ingredients).html_safe %>
                </div>

                <div class="recipe-method">
                  <h3 class="recipe-title">Elkészítés</h3>
                  <%= (@recipe.description).html_safe %>
                </div>
              </div>
            </div>
            <% if(current_user.id == @recipe.user.id) %>
              <div class="action-buttons">
                <%= link_to ("<i class='fa fa-pencil'></i> Szerkesztés").html_safe, edit_recipe_path(@recipe.id), class: 'text-warning' %>
                 <%= link_to ("<i class='fa fa-times'></i> Törlés").html_safe, @recipe, method: :delete, data: { confirm: "Biztos benne?" }, class: 'text-danger' %>
              </div>
            <% end %>
          </article>
        </div>
      </div>
      <div class="col-4">
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow"><%= @recipe.user.username %></span>
          </h4>
          <div class="about-widget">
            <% if @recipe.user.avatar.thumb.url %>
              <%= image_tag @recipe.user.avatar.thumb.url, class: 'img-circle' %>
            <% else %>
              <%= image_tag 'avatar_default.png', class: 'img-circle' %>
            <% end %>
            <h2 class="about-me-heading"><%= @recipe.user.lastname %> <%= @recipe.user.firstname %></h2>
            <% if @recipe.user.description %>
              <p><%= @recipe.user.description %></p>
            <% end %>
          </div>
        </aside>
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow">Kategóriák</span>
          </h4>
          <ul class="category-menu">
            <% for category in RecipeCategory.all %>
              <% if category.recipe_ids.length > 0  %>
                <li>
                  <a href="<%= recipe_category_path(category.id) %>"><%= category.name %> <span>(<%= category.recipe_ids.length %>)</span></a>
                </li>
              <% end %>
            <% end %>
          </ul>
        </aside>
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow">Utolsó 5 recept</span>
          </h4>
          <ul class="last-recipes">
            <% for @lastrecipe in @lastrecipes %>
              <li>
                <div class="side-item">
                  <% if @lastrecipe.featured_image.url %>
                    <div class="side-image">
                      <% if @lastrecipe.featured_image_url %>
                        <a href="<%= recipe_path(@lastrecipe.id) %>" style="background-image: url(<%= @lastrecipe.featured_image_url %>)"></a>
                      <% else %>
                        <a href="<%= recipe_path(@lastrecipe.id) %>"></a>
                      <% end %>
                    </div>
                  <% end %>
                  <div class="side-item-text">
                    <h4>
                      <%= link_to @lastrecipe.title, recipe_path(@lastrecipe.id) %>
                    </h4>
                    <div class="side-item-meta"><%= l @lastrecipe.created_at %></div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </aside>
      </div>
    </div>
  </div>
</section>