config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get     '/regisztracio',                 to: 'users#new'
  post    '/regisztracio',                 to: 'users#create'
  
  scope(path_names: { edit: 'szerkesztes' }) do
    resources :users, path: 'felhasznalok', except: [:new, :create]
  end

  get    '/bejelentkezes',   to: 'session#new'
  post   '/bejelentkezes',   to: 'session#create'
  delete '/kijelentkezes',   to: 'session#destroy'

  scope(path_names: { new: 'uj', edit: 'szerkesztes' }) do
    resources :posts, path: 'blog'
  end

  scope(path_names: { new: 'uj', edit: 'szerkesztes'}) do
    resources :recipes, path: 'receptek'
  end

  get   '/kategoria/:id', to: 'recipe_categories#show', as: 'recipe_category'
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :recipes, dependent: :destroy
  attr_accessor :remember_token
  before_save   :downcase_email
  validates :username, presence: true, length: {maximum: 50, minimum: 4}, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: {maximum: 255, minimum: 5}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates_processing_of :avatar
  validate :image_size_validation

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    def image_size_validation
      errors[:avatar] << "nem lehett nagyobb, mint 500 KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.order('users.username ASC').paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Sikeres regisztráció!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Adatlap frissítve."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).limit(5)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Felhasználó törölve"
    redirect_to users_url
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Kérjük jelentkezzen be."
      redirect_to bejelentkezes_path
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :firstname, :lastname, :description, :avatar)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="col-12 col-md-3">
  <article id="user-<%= user.id %>" class="user-card">
    <a href="<%= users_path %>/<%= user.id %>" class="user-card-inner">
      <% if user.avatar.thumb.url %>
        <%= image_tag user.avatar.thumb.url, class: 'img-circle' %>
      <% else %>
        <%= image_tag 'avatar_default.png', class: 'img-circle' %>
      <% end %>
      <h4><%= user.username %></h4>
    </a>
    <div class="taskbar">
      <% if current_user?(user) %>
      <%= link_to ("<i class='fa fa-pencil'></i>").html_safe, edit_user_path(current_user), class: 'text-warning' %>
      <% end %>
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to ("<i class='fa fa-times'></i>").html_safe, user, method: :delete,
                                      data: { confirm: "Biztos benne?" }, class: 'text-danger' %>
      <% end %>
    </div>
  </article>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Adatlap szerkesztése") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col col-sm-6">
      <%= form_for(@user, html: { multipart: true }) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :username, 'Felhasználónév:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-user"></i>
            </div>
            <%= f.text_field :username, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, 'E-mail cím:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-envelope"></i>
            </div>
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Jelszó:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-key"></i>
            </div>
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'Jelszó ismét:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-key"></i>
            </div>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="col col-md-6">
            <div class="form-group">
              <%= f.label :lastname, 'Vezetéknév:' %>
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-address-card"></i>
                </div>
                <%= f.text_field :lastname, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="col col-md-6">
            <div class="form-group">
              <%= f.label :firstname, 'Keresztnév:' %>
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-address-card"></i>
                </div>
                <%= f.text_field :firstname, class: "form-control" %>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Bemutatkozás:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-pencil"></i>
            </div>
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>
        <div class="form-group text-center">
          <% if f.object.avatar? %>
            <%= image_tag f.object.avatar.thumb.url, class: 'img-circle' %>
          <% end %>
          <div class="form-avatar">
            <%= f.label :avatar, 'Avatar feltöltése' %>
            <%= f.file_field :avatar, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Frissítés", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Felhasználó lista') %>

<div class="container">
  <div class="row">
    <div class="col">
      <%= will_paginate %>
      <div class="users">
        <div class="row">
          <%= render @users %>
        </div>
      </div>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Regisztráció") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col col-sm-6">
      <%= form_for(@user, url: regisztracio_path, html: { multipart: true }) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="form-group">
          <%= f.label :username, 'Felhasználónév:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-user"></i>
            </div>
            <%= f.text_field :username, class: "form-control", placeholder: "Adja meg felhasználónevét" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, 'E-mail cím:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-envelope"></i>
            </div>
            <%= f.email_field :email, class: "form-control", placeholder: "Adja meg email címét" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Jelszó:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-key"></i>
            </div>
            <%= f.password_field :password, class: "form-control", placeholder: "Adja meg jelszavát" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'Jelszó ismét:' %>
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-key"></i>
            </div>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Adja meg jelszavát ismét" %>
          </div>
        </div>
        <div class="form-group text-center">
          <div class="form-avatar">
            <%= f.label :avatar, 'Avatar feltöltése' %>
            <%= f.file_field :avatar, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Regisztráció", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Adatlap") %>

<section id="user-sheet">
  <div class="container">
    <div class="row">
      <div class="col-8">
        <% if @user.recipes %>
          <header class="page-content text-center">
            <hr>
            <h2 class="text-uppercase">Utolsó 5 receptem</h2>
            <hr>
          </header>
          <div class="row">
            <%= render @user.recipes %>
          </div>
        <% end %>
        <% if @user.admin? %>
          <header class="page-content text-center">
            <hr>
            <h2 class="text-uppercase">Utolsó 5 bejegyzésem</h2>
            <hr>
          </header>
          <%= render @posts %>
        <% end %>
      </div>
      <div class="col-4">
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow"><%= @user.username %> profilja</span>
          </h4>
          <div class="about-widget">
            <% if @user.avatar.thumb.url %>
              <%= image_tag @user.avatar.thumb.url, class: 'img-circle' %>
            <% else %>
              <%= image_tag 'avatar_default.png', class: 'img-circle' %>
            <% end %>
            <h2 class="about-me-heading"><%= @user.lastname %> <%= @user.firstname %></h2>
            <% if @user.description %>
              <p><%= @user.description %></p>
            <% end %>
            <% if logged_in? && current_user?(@user) %>
              <div class="text-center">
                <%= link_to "Szerkesztés", edit_user_path(current_user) %>
              </div>
            <% end %>
          </div>
        </aside>
      </div>
    </div>
  </div>
</section>