config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get     '/regisztracio',                 to: 'users#new'
  post    '/regisztracio',                 to: 'users#create'
  
  scope(path_names: { edit: 'szerkesztes' }) do
    resources :users, path: 'felhasznalok', except: [:new, :create]
  end

  get    '/bejelentkezes',   to: 'session#new'
  post   '/bejelentkezes',   to: 'session#create'
  delete '/kijelentkezes',   to: 'session#destroy'

  scope(path_names: { new: 'uj', edit: 'szerkesztes' }) do
    resources :posts, path: 'blog'
  end

  scope(path_names: { new: 'uj', edit: 'szerkesztes'}) do
    resources :recipes, path: 'receptek'
  end

  get   '/kategoria/:id', to: 'recipe_categories#show', as: 'recipe_category'
  
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :featured_image, ImageUploader
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  private

    def image_size_validation
      errors[:featured_image] << "nem lehett nagyobb, mint 1 MB" if avatar.size > 1.0.megabytes
    end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :recipes, dependent: :destroy
  attr_accessor :remember_token
  before_save   :downcase_email
  validates :username, presence: true, length: {maximum: 50, minimum: 4}, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: {maximum: 255, minimum: 5}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates_processing_of :avatar
  validate :image_size_validation

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    def image_size_validation
      errors[:avatar] << "nem lehett nagyobb, mint 500 KB" if avatar.size > 0.5.megabytes
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :admin_user, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.order('posts.created_at DESC').paginate(page: params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "A bejegyzést sikeresen közzétettük!"
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Bejegyzés frissítve."
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Bejegyzés törölve"
    redirect_to posts_url
  end
  
  private

    def post_params
      params.require(:post).permit(:title, :content, :user_id, :featured_image)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<article id="post-<%= post.id %>" class="post page-content">
  <div class="row">
    <div class="col-12 col-sm-3">
      <div class="thumbnail">
        <% if post.featured_image_url %>
          <a href="<%= post_path(post.id) %>" style="background-image: url(<%= post.featured_image_url %>)"></a>
        <% else %>
          <a href="<%= post_path(post.id) %>"></a>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-sm-9">
      <h3><%= link_to post.title, post_path(post.id) %></h3>
      <div class="info">
        <% @user = User.find(post.user_id) %>
        <strong>Szerző:</strong> <author><%= link_to @user.username, user_path(@user)  %></author>
        - <time><%= time_ago_in_words(post.created_at) %></time>
        <% if(current_user.admin?) %>
          - <%= link_to ("<i class='fa fa-pencil'></i>").html_safe, edit_post_path(post.id), class: 'text-warning' %>
          <%= link_to ("<i class='fa fa-times'></i>").html_safe, post, method: :delete, data: { confirm: "Biztos benne?" }, class: 'text-danger' %>
        <% end %>
      </div>
      <p><%= truncate(strip_tags(post.content), length: 400, omission: '...') %></p>
    </div>
  </div>
  <hr>
</article>

app/views/posts/edit.html.erb
<% provide(:title, "Bejegyzés szerkesztése") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <% if @post.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <p><%= pluralize(@post.errors.count, "hiba") %> merült fel a közzététel során:</p>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_for(@post, url: {action: :update}) do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Cím:' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content, 'Tartalom:' %>
          <%= f.text_area :content, id: 'froala', class: 'form-control' %>
        </div>
        <div class="form-group text-center">
          <% if f.object.featured_image? %>
            <%= image_tag f.object.featured_image.thumb.url, class: 'img-fluid' %>
          <% end %>
          <div class="form-avatar">
            <%= f.label :featured_image, 'Kép feltöltése' %>
            <%= f.file_field :featured_image, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Frissítés", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Blog") %>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="posts">
        <%= render @posts %>        
      </div>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Új bejegytés") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <% if @post.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <p><%= pluralize(@post.errors.count, "hiba") %> merült fel a közzététel során:</p>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_for(@post, url: {action: :create}) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
          <%= f.label :title, 'Cím:' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content, 'Tartalom:' %>
          <%= f.text_area :content, id: 'froala', class: 'form-control' %>
        </div>
        <div class="form-group text-center">
          <div class="form-avatar">
            <%= f.label :featured_image, 'Kép feltöltése' %>
            <%= f.file_field :featured_image, class: "form-upload" %>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "Küldés", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<section id="user-sheet">
  <div class="container">
    <div class="row">
      <div class="col-8">
        <div class="page-content">
          <h2><%= @post.title %></h2>
          <% if @post.featured_image.url %>
            <%= image_tag @post.featured_image.url, class: 'img-fluid' %>
          <% end %>
          <%= (@post.content).html_safe %>
        </div>
      </div>
      <div class="col-4">
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow">Szerző</span>
          </h4>
          <div class="about-widget">
            <% if @post.user.avatar.thumb.url %>
              <%= image_tag @post.user.avatar.thumb.url, class: 'img-circle' %>
            <% else %>
              <%= image_tag 'avatar_default.png', class: 'img-circle' %>
            <% end %>
            <h2 class="about-me-heading"><%= @post.user.lastname %> <%= @post.user.firstname %></h2>
            <% if @post.user.description %>
              <p><%= @post.user.description %></p>
            <% end %>
          </div>
        </aside>
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow">Kategóriák</span>
          </h4>
          <ul class="category-menu">
            <% for category in RecipeCategory.all %>
              <% if category.recipe_ids.length > 0  %>
                <li>
                  <a href="<%= recipe_category_path(category.id) %>"><%= category.name %> <span>(<%= category.recipe_ids.length %>)</span></a>
                </li>
              <% end %>
            <% end %>
          </ul>
        </aside>
        <aside class="widget">
          <h4 class="widget-title">
            <span class="inner-arrow">Utolsó 5 recept</span>
          </h4>
          <ul class="last-recipes">
            <% for @lastrecipe in Recipe.order('recipes.created_at DESC').limit(5) %>
              <li>
                <div class="side-item">
                  <% if @lastrecipe.featured_image.url %>
                    <div class="side-image">
                      <% if @lastrecipe.featured_image_url %>
                        <a href="<%= recipe_path(@lastrecipe.id) %>" style="background-image: url(<%= @lastrecipe.featured_image_url %>)"></a>
                      <% else %>
                        <a href="<%= recipe_path(@lastrecipe.id) %>"></a>
                      <% end %>
                    </div>
                  <% end %>
                  <div class="side-item-text">
                    <h4>
                      <%= link_to @lastrecipe.title, recipe_path(@lastrecipe.id) %>
                    </h4>
                    <div class="side-item-meta"><%= l @lastrecipe.created_at %></div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </aside>
      </div>
    </div>
  </div>
</section>