config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get     '/regisztracio',                 to: 'users#new'
  post    '/regisztracio',                 to: 'users#create'
  
  scope(path_names: { edit: 'szerkesztes' }) do
    resources :users, path: 'felhasznalok', except: [:new, :create]
  end

  get    '/bejelentkezes',   to: 'session#new'
  post   '/bejelentkezes',   to: 'session#create'
  delete '/kijelentkezes',   to: 'session#destroy'

  scope(path_names: { new: 'uj', edit: 'szerkesztes' }) do
    resources :posts, path: 'blog'
  end

  scope(path_names: { new: 'uj', edit: 'szerkesztes'}) do
    resources :recipes, path: 'receptek'
  end

  get   '/kategoria/:id', to: 'recipe_categories#show', as: 'recipe_category'
  
end

app/views/layouts/_footer.html.erb
<footer id="footer-section">
  <div class="container">
    <div class="footer-logo-copyright">
      <div class="footer-logo">
        <a href="<%= request.base_url %>">
          <%= image_tag 'logo-footer.svg' %>
        </a>
      </div>
      <div class="footer-copyright">
        <p>&copy; 2017 - Cégnév. Minden jog fenntartva.</p>
      </div>
      <div class="go-to-top-parent">
        <a href="" class="go-to-top">
          <span>
            <i class="fa fa-angle-up"></i><br>
            Az oldal tetejére
          </span>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="inner-header">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="logo">
              <a href="<%= request.base_url %>">
                <%= image_tag 'logo.svg' %>
                <h1 class="sr-only">Chef</h1>
              </a>
          </div>
          <div class="header-slogan">
            <h2 class="header-slogan-text">
              recept blog
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="navigation-sticky-wrapper" class="sticky-wrapper">
    <nav id="navigation">
      <div class="container">
        <div class="row">
          <div class="col">
            <ul class="menu clearfix">
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-home'></i> Főoldal").html_safe, root_path %>
              </li>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-book'></i> Receptek").html_safe, recipes_path %>
              </li>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-users'></i> Felhasználók").html_safe, users_path %>
              </li>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-newspaper-o'></i> Blog").html_safe, posts_path %>
              </li>
            </ul>
          </div>
          <div class="col clearfix">
            <ul class="menu sub-menu pull-right clearfix">
              <% if logged_in? %>
              <li class="menu-item">
                <a href="#"><i class='fa fa-user'></i> Profilom</a>
                <ul class="sub-menu">
                  <li class="menu-item">
                    <%= link_to 'Profilom', current_user %>
                  </li>
                  <% if current_user.admin? %>
                    <li class="menu-item">
                      <%= link_to 'Új bejegyzés', new_post_path %>
                    </li>
                  <% end %>
                  <li class="menu-item">
                    <%= link_to 'Új recept', new_recipe_path %>
                  </li>
                </ul>
              </li>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-sign-out'></i> Kijelentkezés").html_safe, kijelentkezes_path, method: "delete" %>
              </li>
              <% else %>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-sign-in'></i> Bejelentkezés").html_safe, bejelentkezes_path %>
              </li>
              <li class="menu-item">
                <%= link_to ("<i class='fa fa-key'></i> Regisztráció").html_safe, regisztracio_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chef - <%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i|Roboto+Slab:300,400,700&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.1/css/froala_editor.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.1/css/froala_style.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>